### ISSUE TITLE
No detection for these sites

### ISSUE THREAD

**Issue by SwallowYourDreams** [otsmr/inline-popup-blocker#5]
I love the idea behind this add-on, but it does not appear to be working on these sites:

* [https://www.finanzen.net/](https://www.finanzen.net/): Overlay banner, but (as far as I've understood from looking at the HTML) it's realised as an iframe so as to impede shenanigans like the one we're trying to pull off. If you block the iframe via your adblocker, the site will still not work because it lacks scroll bars. Truly annoying.

* [https://youtube.com](https://youtube.com): Redirect banner, redirects to empty page.

**Comment by otsmr** [comment]
That the banner is not recognized at finanzen.net surprises me a bit, actually it should be recognized. The scrolling should (if recognized) normally also work again (in the head they simply use a: overflow: hidden, which I overwrite).

The problem with YouTube or with the new cookie banner from Google I have also noticed. But there I have no idea how to implement this without a blocklist. I have already played around a bit with the banner and as soon as youtube.com the cookie `CONSENT=YES+` is present, is no longer forwarded.

**Comment by SwallowYourDreams** [comment]
> That the banner is not recognized at finanzen.net surprises me a bit, actually it should be recognized.

Does that mean you have checked and it works on your end? That'd be really weird...

> The problem with YouTube or with the new cookie banner from Google I have also noticed. But there I have no idea how to implement this without a blocklist. I have already played around a bit with the banner and as soon as youtube.com the cookie CONSENT=YES+ is present, is no longer forwarded.

Yeah, I imagined the Google banner would be a much tougher nut to crack. I'm sorry I won't be any help with this one since I don't have a clue what's happening "behind the scenes".

**Comment by otsmr** [comment]
> Does that mean you have checked and it works on your end? That'd be really weird...

No, the banner was not blocked at me too, I was just wondering, because actually it should be recognized. I have now also found the actual error. The banner is invisible at the beginning (display: none), why it is first ignored. After a few seconds it becomes visible (display: block). But that is a change of the attribute, and they are ignored after a change:

```js
observer.observe(document.body, { attributes: false, childList: true, subtree: true })
````

With the Google banner I still have to think about something, that is also recognized, but Google can not be tricked as easily as the other pages with the wrong UserAgent trick :D
